const trips = [
  {
    title: "Summer Vacation",
    initialpoint: "New York",
    destination: {
      country: "France",
      location: "Paris",
    },
    startDate: "2023-07-15",
    endDate: "2023-07-30",
    description: "A relaxing trip to explore the beauty of Paris.",
    budget: 2500,
    status: "Planned",
  },
  {
    title: "Winter Adventure",
    initialpoint: "Toronto",
    destination: {
      country: "Canada",
      location: "Banff National Park",
    },
    startDate: "2023-12-20",
    endDate: "2023-12-30",
    description: "A snowy adventure in the Canadian Rockies.",
    budget: 3000,
    status: "Planned",
  },
  {
    title: "Cultural Exploration",
    initialpoint: "Los Angeles",
    destination: {
      country: "Japan",
      location: "Kyoto",
    },
    startDate: "2023-11-01",
    endDate: "2023-11-10",
    description: "Exploring the rich culture and history of Kyoto.",
    budget: 2000,
    status: "OnTrip",
  },
  {
    title: "Beach Getaway",
    initialpoint: "London",
    destination: {
      country: "Maldives",
      location: "Malé",
    },
    startDate: "2023-09-05",
    endDate: "2023-09-15",
    description: "Relaxing on the pristine beaches of the Maldives.",
    budget: 5000,
    status: "Complete",
  },
  {
    title: "Safari Expedition",
    initialpoint: "Nairobi",
    destination: {
      country: "Kenya",
      location: "Maasai Mara",
    },
    startDate: "2023-08-10",
    endDate: "2023-08-20",
    description: "A thrilling safari experience in Maasai Mara.",
    budget: 4000,
    status: "Delayed",
  },
  {
    title: "City Break",
    initialpoint: "Berlin",
    destination: {
      country: "Italy",
      location: "Rome",
    },
    startDate: "2023-10-01",
    endDate: "2023-10-07",
    description: "Exploring the historic landmarks of Rome.",
    budget: 1500,
    status: "Planned",
  },
  {
    title: "Mountain Trek",
    initialpoint: "Kathmandu",
    destination: {
      country: "Nepal",
      location: "Everest Base Camp",
    },
    startDate: "2023-05-01",
    endDate: "2023-05-15",
    description: "Trekking to the base camp of Mount Everest.",
    budget: 2500,
    status: "Complete",
  },
  {
    title: "Desert Adventure",
    initialpoint: "Abu Dhabi",
    destination: {
      country: "United Arab Emirates",
      location: "Dubai",
    },
    startDate: "2023-06-10",
    endDate: "2023-06-20",
    description: "Exploring the deserts and modern marvels of Dubai.",
    budget: 3500,
    status: "OnTrip",
  },
  {
    title: "Road Trip",
    initialpoint: "Chicago",
    destination: {
      country: "USA",
      location: "Route 66",
    },
    startDate: "2023-07-01",
    endDate: "2023-07-14",
    description: "A classic road trip along Route 66.",
    budget: 3000,
    status: "Planned",
  },
  {
    title: "Island Hopping",
    initialpoint: "Athens",
    destination: {
      country: "Greece",
      location: "Santorini",
    },
    startDate: "2023-08-01",
    endDate: "2023-08-10",
    description: "Exploring the beautiful islands of Greece.",
    budget: 2800,
    status: "Complete",
  },
];
module.exports = { data: trips };
